package config

type LocationInfo struct {
	Code    string            // Country Code (e.g., "IN" for India)
	Regions map[string]string // Key: Region Name (e.g., "California"), Value: Region Code (e.g., "US-CA")
}

var CountryAbbreviations = map[string]LocationInfo{
	"Albania":              {Code: "AL", Regions: nil},
	"Algeria":              {Code: "DZ", Regions: nil},
	"Angola":               {Code: "AO", Regions: nil},
	"Argentina":            {Code: "AR", Regions: nil},
	"Armenia":              {Code: "AM", Regions: nil},
	"Australia":            {Code: "AU", Regions: nil},
	"Austria":              {Code: "AT", Regions: nil},
	"Azerbaijan":           {Code: "AZ", Regions: nil},
	"Bahrain":              {Code: "BH", Regions: nil},
	"Bangladesh":           {Code: "BD", Regions: nil},
	"Belarus":              {Code: "BY", Regions: nil},
	"Belgium":              {Code: "BE", Regions: nil},
	"Benin":                {Code: "BJ", Regions: nil},
	"Bolivia":              {Code: "BO", Regions: nil},
	"Bosnia & Herzegovina": {Code: "BA", Regions: nil},
	"Brazil":               {Code: "BR", Regions: nil},
	"Bulgaria":             {Code: "BG", Regions: nil},
	"Burkina Faso":         {Code: "BF", Regions: nil},
	"Cambodia":             {Code: "KH", Regions: nil},
	"Cameroon":             {Code: "CM", Regions: nil},
	"Canada":               {Code: "CA", Regions: nil},
	"Chile":                {Code: "CL", Regions: nil},
	"Colombia":             {Code: "CO", Regions: nil},
	"Congo - Kinshasa":     {Code: "CD", Regions: nil},
	"Costa Rica":           {Code: "CR", Regions: nil},
	"Côte d’Ivoire":        {Code: "CI", Regions: nil},
	"Croatia":              {Code: "HR", Regions: nil},
	"Cuba":                 {Code: "CU", Regions: nil},
	"Cyprus":               {Code: "CY", Regions: nil},
	"Czechia":              {Code: "CZ", Regions: nil},
	"Denmark":              {Code: "DK", Regions: nil},
	"Dominican Republic":   {Code: "DO", Regions: nil},
	"Ecuador":              {Code: "EC", Regions: nil},
	"Egypt":                {Code: "EG", Regions: nil},
	"El Salvador":          {Code: "SV", Regions: nil},
	"Estonia":              {Code: "EE", Regions: nil},
	"Ethiopia":             {Code: "ET", Regions: nil},
	"Finland":              {Code: "FI", Regions: nil},
	"France":               {Code: "FR", Regions: nil},
	"Georgia":              {Code: "GE", Regions: nil},
	"Germany":              {Code: "DE", Regions: nil},
	"Ghana":                {Code: "GH", Regions: nil},
	"Greece":               {Code: "GR", Regions: nil},
	"Guatemala":            {Code: "GT", Regions: nil},
	"Haiti":                {Code: "HT", Regions: nil},
	"Honduras":             {Code: "HN", Regions: nil},
	"Hong Kong":            {Code: "HK", Regions: nil},
	"Hungary":              {Code: "HU", Regions: nil},
	"India": {Code: "IN", Regions: map[string]string{
		"Andaman and Nicobar Islands": "AN",
		"Andhra Pradesh":              "AP",
		"Arunachal Pradesh":           "AR",
		"Assam":                       "AS",
		"Bihar":                       "BR",
		"Chandigarh":                  "CH",
		"Chhattisgarh":                "CT",
		"Dadra and Nagar Haveli":      "DN",
		"Daman and Diu":               "DD",
		"Delhi":                       "DL",
		"Goa":                         "GA",
		"Gujarat":                     "GJ",
		"Haryana":                     "HR",
		"Himachal Pradesh":            "HP",
		"Jammu and Kashmir":           "JK",
		"Jharkhand":                   "JH",
		"Karnataka":                   "KA",
		"Kerala":                      "KL",
		"Lakshadweep":                 "LD",
		"Madhya Pradesh":              "MP",
		"Maharashtra":                 "MH",
		"Manipur":                     "MN",
		"Meghalaya":                   "ML",
		"Mizoram":                     "MZ",
		"Nagaland":                    "NL",
		"Odisha":                      "OR",
		"Puducherry":                  "PY",
		"Punjab":                      "PB",
		"Rajasthan":                   "RJ",
		"Sikkim":                      "SK",
		"Tamil Nadu":                  "TN",
		"Telangana":                   "TG",
		"Tripura":                     "TR",
		"Uttar Pradesh":               "UP",
		"Uttarakhand":                 "UT",
		"West Bengal":                 "WB",
	}},
	"Indonesia":            {Code: "ID", Regions: nil},
	"Iran":                 {Code: "IR", Regions: nil},
	"Iraq":                 {Code: "IQ", Regions: nil},
	"Ireland":              {Code: "IE", Regions: nil},
	"Israel":               {Code: "IL", Regions: nil},
	"Italy":                {Code: "IT", Regions: nil},
	"Jamaica":              {Code: "JM", Regions: nil},
	"Japan":                {Code: "JP", Regions: nil},
	"Jordan":               {Code: "JO", Regions: nil},
	"Kazakhstan":           {Code: "KZ", Regions: nil},
	"Kenya":                {Code: "KE", Regions: nil},
	"Kuwait":               {Code: "KW", Regions: nil},
	"Kyrgyzstan":           {Code: "KG", Regions: nil},
	"Latvia":               {Code: "LV", Regions: nil},
	"Lebanon":              {Code: "LB", Regions: nil},
	"Libya":                {Code: "LY", Regions: nil},
	"Lithuania":            {Code: "LT", Regions: nil},
	"Malaysia":             {Code: "MY", Regions: nil},
	"Mali":                 {Code: "ML", Regions: nil},
	"Mexico":               {Code: "MX", Regions: nil},
	"Moldova":              {Code: "MD", Regions: nil},
	"Morocco":              {Code: "MA", Regions: nil},
	"Mozambique":           {Code: "MZ", Regions: nil},
	"Myanmar (Burma)":      {Code: "MM", Regions: nil},
	"Nepal":                {Code: "NP", Regions: nil},
	"Netherlands":          {Code: "NL", Regions: nil},
	"New Zealand":          {Code: "NZ", Regions: nil},
	"Nicaragua":            {Code: "NI", Regions: nil},
	"Nigeria":              {Code: "NG", Regions: nil},
	"North Macedonia":      {Code: "MK", Regions: nil},
	"Norway":               {Code: "NO", Regions: nil},
	"Oman":                 {Code: "OM", Regions: nil},
	"Pakistan":             {Code: "PK", Regions: nil},
	"Palestine":            {Code: "PS", Regions: nil},
	"Panama":               {Code: "PA", Regions: nil},
	"Paraguay":             {Code: "PY", Regions: nil},
	"Peru":                 {Code: "PE", Regions: nil},
	"Philippines":          {Code: "PH", Regions: nil},
	"Poland":               {Code: "PL", Regions: nil},
	"Portugal":             {Code: "PT", Regions: nil},
	"Puerto Rico":          {Code: "PR", Regions: nil},
	"Qatar":                {Code: "QA", Regions: nil},
	"Romania":              {Code: "RO", Regions: nil},
	"Russia":               {Code: "RU", Regions: nil},
	"Saudi Arabia":         {Code: "SA", Regions: nil},
	"Senegal":              {Code: "SN", Regions: nil},
	"Serbia":               {Code: "RS", Regions: nil},
	"Singapore":            {Code: "SG", Regions: nil},
	"Slovakia":             {Code: "SK", Regions: nil},
	"Slovenia":             {Code: "SI", Regions: nil},
	"South Africa":         {Code: "ZA", Regions: nil},
	"South Korea":          {Code: "KR", Regions: nil},
	"Spain":                {Code: "ES", Regions: nil},
	"Sri Lanka":            {Code: "LK", Regions: nil},
	"Sweden":               {Code: "SE", Regions: nil},
	"Switzerland":          {Code: "CH", Regions: nil},
	"Syria":                {Code: "SY", Regions: nil},
	"Taiwan":               {Code: "TW", Regions: nil},
	"Tanzania":             {Code: "TZ", Regions: nil},
	"Thailand":             {Code: "TH", Regions: nil},
	"Trinidad & Tobago":    {Code: "TT", Regions: nil},
	"Tunisia":              {Code: "TN", Regions: nil},
	"Türkiye":              {Code: "TR", Regions: nil},
	"Turkmenistan":         {Code: "TM", Regions: nil},
	"Uganda":               {Code: "UG", Regions: nil},
	"Ukraine":              {Code: "UA", Regions: nil},
	"United Arab Emirates": {Code: "AE", Regions: nil},
	"United Kingdom":       {Code: "UK", Regions: nil},
	"United States":        {Code: "US", Regions: nil},
	"Uruguay":              {Code: "UY", Regions: nil},
	"Uzbekistan":           {Code: "UZ", Regions: nil},
	"Venezuela":            {Code: "VE", Regions: nil},
	"Vietnam":              {Code: "VN", Regions: nil},
	"Yemen":                {Code: "YE", Regions: nil},
	"Zambia":               {Code: "ZM", Regions: nil},
	"Zimbabwe":             {Code: "ZW", Regions: nil},
}
